[package]
name = "ma_keller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
nalgebra = "0.32.3"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
